// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJXSddrYeJdSsHgbv7IzJ2feD8o8X7tI',
    appId: '1:1007187799393:web:bff7965b605fca8c046920',
    messagingSenderId: '1007187799393',
    projectId: 'attendances-e9f6d',
    authDomain: 'attendances-e9f6d.firebaseapp.com',
    storageBucket: 'attendances-e9f6d.firebasestorage.app',
    measurementId: 'G-NM7M8LQBN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlOGWqAdPr7zuBfaOFctnGT2S3nBkAmzg',
    appId: '1:1007187799393:android:a266bcb34407d048046920',
    messagingSenderId: '1007187799393',
    projectId: 'attendances-e9f6d',
    storageBucket: 'attendances-e9f6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATAga43Y4CY_y_rLOQSUukhsscSLkmoVs',
    appId: '1:1007187799393:ios:b7b865cb9c0cc61b046920',
    messagingSenderId: '1007187799393',
    projectId: 'attendances-e9f6d',
    storageBucket: 'attendances-e9f6d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATAga43Y4CY_y_rLOQSUukhsscSLkmoVs',
    appId: '1:1007187799393:ios:b7b865cb9c0cc61b046920',
    messagingSenderId: '1007187799393',
    projectId: 'attendances-e9f6d',
    storageBucket: 'attendances-e9f6d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhJXSddrYeJdSsHgbv7IzJ2feD8o8X7tI',
    appId: '1:1007187799393:web:005f97e6c4135f05046920',
    messagingSenderId: '1007187799393',
    projectId: 'attendances-e9f6d',
    authDomain: 'attendances-e9f6d.firebaseapp.com',
    storageBucket: 'attendances-e9f6d.firebasestorage.app',
    measurementId: 'G-1LPYBS44DX',
  );
}
